//! The bootstrap frame, and the diagnostic codes the broker may emit.
//!
//! Everything here is fixed-size or length-prefixed with a hard cap, so
//! "malformed", "truncated" and "oversized" are decidable before any of the
//! bytes are trusted. A text protocol would have made those three states blur
//! into each other, and the broker's whole contract is that it exits *before*
//! validating a root, binding, locking or opening a database when its input
//! is anything but one exact frame.

/// Distinguishes this framing from anything else that might be piped in, and
/// changes if the layout ever does.
pub const MAGIC: &[u8; 16] = b"SFO-BOOTSTRAP-1\n";
pub const VERSION: u16 = 1;

/// The launch key the supervisor will later authenticate with. Generated by
/// the parent, delivered only on stdin, never on argv, in the environment, or
/// on disk — anything a sibling process can read is not a secret.
pub const KEY_LEN: usize = 32;
pub const NONCE_LEN: usize = 16;
pub const MAX_ROOT_LEN: usize = 1024;

/// The largest well-formed frame. One byte more is oversized, and is refused
/// without being parsed.
pub const MAX_FRAME_LEN: usize = MAGIC.len() + 2 + KEY_LEN + NONCE_LEN + 2 + MAX_ROOT_LEN;

/// Fixed, value-free codes. A diagnostic must never carry a path, a key, or
/// anything else that would turn an error channel into a disclosure channel.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Diagnostic {
    BootstrapMissing,
    BootstrapMalformed,
    BootstrapOversized,
    BootstrapTruncated,
    BootstrapVersionUnsupported,
    RootRejected,
    BindFailed,
    AddressMalformed,
    /// No supervisor authenticated before the fixed deadline.
    SupervisorTimeout,
    /// The parent went away between publishing the address and the handshake.
    SupervisorLost,
    /// Something connected and could not prove it holds the launch key.
    SupervisorUnauthenticated,
    /// Another broker already owns this root.
    BrokerAlreadyRunning,
    /// Exclusivity could not be established, which is not permission.
    LockUnavailable,
    /// The store could not be opened; ownership is unknown, not granted.
    StoreUnavailable,
}

impl Diagnostic {
    pub const fn code(self) -> &'static str {
        match self {
            Diagnostic::BootstrapMissing => "E-BOOTSTRAP-MISSING",
            Diagnostic::BootstrapMalformed => "E-BOOTSTRAP-MALFORMED",
            Diagnostic::BootstrapOversized => "E-BOOTSTRAP-OVERSIZED",
            Diagnostic::BootstrapTruncated => "E-BOOTSTRAP-TRUNCATED",
            Diagnostic::BootstrapVersionUnsupported => "E-BOOTSTRAP-VERSION",
            Diagnostic::RootRejected => "E-ROOT-REJECTED",
            Diagnostic::BindFailed => "E-BIND-FAILED",
            Diagnostic::AddressMalformed => "E-ADDRESS-MALFORMED",
            Diagnostic::SupervisorTimeout => "E-SUPERVISOR-TIMEOUT",
            Diagnostic::SupervisorLost => "E-SUPERVISOR-LOST",
            Diagnostic::SupervisorUnauthenticated => "E-SUPERVISOR-UNAUTHENTICATED",
            Diagnostic::BrokerAlreadyRunning => "E-BROKER-ALREADY-RUNNING",
            Diagnostic::LockUnavailable => "E-LOCK-UNAVAILABLE",
            Diagnostic::StoreUnavailable => "E-STORE-UNAVAILABLE",
        }
    }
}

impl std::fmt::Display for Diagnostic {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.code())
    }
}

/// One parsed bootstrap frame. The key is owned here and nowhere else.
pub struct Bootstrap {
    pub launch_key: [u8; KEY_LEN],
    pub nonce: [u8; NONCE_LEN],
    pub root: std::path::PathBuf,
}

impl std::fmt::Debug for Bootstrap {
    /// Hand-written and value-free: a derived `Debug` would print the launch
    /// key the moment anything logged this struct.
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("Bootstrap")
            .field("launch_key", &"<redacted>")
            .field("nonce", &"<redacted>")
            .field("root", &"<redacted>")
            .finish()
    }
}

/// Encode a frame. Used by the parent and by tests; there is one encoder so
/// the two cannot drift.
pub fn encode(
    launch_key: &[u8; KEY_LEN],
    nonce: &[u8; NONCE_LEN],
    root: &std::path::Path,
) -> Vec<u8> {
    let root = root.as_os_str().to_string_lossy();
    let root = root.as_bytes();
    let mut frame = Vec::with_capacity(MAX_FRAME_LEN);
    frame.extend_from_slice(MAGIC);
    frame.extend_from_slice(&VERSION.to_le_bytes());
    frame.extend_from_slice(launch_key);
    frame.extend_from_slice(nonce);
    frame.extend_from_slice(&(root.len() as u16).to_le_bytes());
    frame.extend_from_slice(root);
    frame
}

/// Parse exactly one frame from bytes already read under the cap.
pub fn decode(bytes: &[u8]) -> Result<Bootstrap, Diagnostic> {
    if bytes.is_empty() {
        return Err(Diagnostic::BootstrapMissing);
    }
    if bytes.len() > MAX_FRAME_LEN {
        return Err(Diagnostic::BootstrapOversized);
    }
    let mut cursor = 0;
    let take = |cursor: &mut usize, n: usize| -> Result<&[u8], Diagnostic> {
        let end = cursor
            .checked_add(n)
            .ok_or(Diagnostic::BootstrapMalformed)?;
        let slice = bytes
            .get(*cursor..end)
            .ok_or(Diagnostic::BootstrapTruncated)?;
        *cursor = end;
        Ok(slice)
    };

    if take(&mut cursor, MAGIC.len())? != MAGIC.as_slice() {
        return Err(Diagnostic::BootstrapMalformed);
    }
    let version = u16::from_le_bytes(take(&mut cursor, 2)?.try_into().expect("2 bytes"));
    if version != VERSION {
        return Err(Diagnostic::BootstrapVersionUnsupported);
    }
    let mut launch_key = [0u8; KEY_LEN];
    launch_key.copy_from_slice(take(&mut cursor, KEY_LEN)?);
    let mut nonce = [0u8; NONCE_LEN];
    nonce.copy_from_slice(take(&mut cursor, NONCE_LEN)?);
    let root_len = u16::from_le_bytes(take(&mut cursor, 2)?.try_into().expect("2 bytes")) as usize;
    if root_len == 0 || root_len > MAX_ROOT_LEN {
        return Err(Diagnostic::BootstrapMalformed);
    }
    let root = take(&mut cursor, root_len)?;
    if cursor != bytes.len() {
        // Trailing bytes are not ignored: the frame is exact or it is nothing.
        return Err(Diagnostic::BootstrapMalformed);
    }
    let root = std::str::from_utf8(root).map_err(|_| Diagnostic::BootstrapMalformed)?;
    Ok(Bootstrap {
        launch_key,
        nonce,
        root: std::path::PathBuf::from(root),
    })
}

/// Read one bounded frame. Reads at most one byte more than a legal frame, so
/// an oversized input is refused rather than buffered.
pub fn read_frame(reader: &mut impl std::io::Read) -> Result<Bootstrap, Diagnostic> {
    use std::io::Read;
    let mut bytes = Vec::new();
    let limit = (MAX_FRAME_LEN + 1) as u64;
    reader
        .take(limit)
        .read_to_end(&mut bytes)
        .map_err(|_| Diagnostic::BootstrapMalformed)?;
    decode(&bytes)
}

// ------------------------------------------------------------- address ----

/// Published on stdout once the listener is bound, so the parent learns where
/// to connect. Non-secret by construction: a port, the version, and the nonce
/// the parent already sent. The launch key is never echoed — a parent that
/// needed it back would be a parent that had lost it.
pub const ADDRESS_MAGIC: &[u8; 14] = b"SFO-ADDRESS-1\n";
pub const ADDRESS_FRAME_LEN: usize = ADDRESS_MAGIC.len() + 2 + 2 + NONCE_LEN;

pub fn encode_address(port: u16, nonce: &[u8; NONCE_LEN]) -> Vec<u8> {
    let mut frame = Vec::with_capacity(ADDRESS_FRAME_LEN);
    frame.extend_from_slice(ADDRESS_MAGIC);
    frame.extend_from_slice(&VERSION.to_le_bytes());
    frame.extend_from_slice(&port.to_le_bytes());
    frame.extend_from_slice(nonce);
    frame
}

/// Decode an address frame. Used by the parent and by tests.
pub fn decode_address(bytes: &[u8]) -> Result<(u16, [u8; NONCE_LEN]), Diagnostic> {
    if bytes.len() != ADDRESS_FRAME_LEN {
        return Err(Diagnostic::AddressMalformed);
    }
    if &bytes[..ADDRESS_MAGIC.len()] != ADDRESS_MAGIC.as_slice() {
        return Err(Diagnostic::AddressMalformed);
    }
    let mut at = ADDRESS_MAGIC.len();
    let version = u16::from_le_bytes(bytes[at..at + 2].try_into().expect("2 bytes"));
    at += 2;
    if version != VERSION {
        return Err(Diagnostic::BootstrapVersionUnsupported);
    }
    let port = u16::from_le_bytes(bytes[at..at + 2].try_into().expect("2 bytes"));
    at += 2;
    let mut nonce = [0u8; NONCE_LEN];
    nonce.copy_from_slice(&bytes[at..at + NONCE_LEN]);
    Ok((port, nonce))
}
